add snippet to enable testing
zyxar/Sublime-CMakeLists pull request #50
Opened 2020-12-20 11:26 UTC by arcturus140

this PR improves snippet to enable testing

before: autocomplete adds `enable_testing()`, leaving the cursor inside brackets. This is annoying, the function has no arguments.

after: autocomplete adds `enable_testing()` and a line break. If the new line is too intrusive i can remove it, but i always have this command in a single line for readability. 

as far as i can see the tool automatically skips new snippets on generation, so we don't have any duplicates?

2020-12-22 22:05 UTC, rwols requested changes

2020-12-22 22:05 UTC, rwols commented on Snippets/enable_testing.sublime-snippet
> +
For now, please remove this newline.

2020-12-23 11:13 UTC, arcturus140 commented
@rwols done

2020-12-23 18:36 UTC, merged

2020-12-23 18:36 UTC, rwols commented
Thanks, nice work!